### PR TITLE
Fix typo in reserve_pool metric

### LINKED ISSUE #66: Reserve Pool Metric not reported
There is an incorrect colon added on the `reserve_pool` metric.

https://github.com/prometheus-community/pgbouncer_exporter/blob/master/collector.go#L41

### PR DESCRIPTION
**Pull request by stanhu**
Drop the extra colon.

Closes #66

### CODE REVIEW

**Comment by SuperQ** [comment]
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

**Review by SuperQ — APPROVED** [review]
LGTM, thanks for the fix.

Will merge as soon as the DCO is fixed.

**Comment by stanhu** [comment]
@SuperQ Could you merge and release a new version?

**Comment by klynch** [comment]
Thanks for getting this! I'd have done it myself, but getting a DCO is presently complicated.

**Pull request merged**
